### ISSUE TITLE
Problem in building package

### ISSUE THREAD

**Issue by yellowjs0304** [iKrishneel/mask_rcnn_ros#1]
Thank you for sharing this project.
I have a question with your readme scripts.

first, in your script[Downloading the package], after git clone your package in my catkin_ws,
I understood the command ''cd jsk_hsr_wrs'' meaning is to move to my ros catkin workspace.
I followed it, and other command did well.
But after that(in compilation) I can't build my workspace with '' user@user: ~/catkin_ws$ caktin_make'' this command.

It returns like this error
`Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genjava/cmake/../../../lib/genjava/genjava_gradle_project.py", line 14, in <module>
    genjava.main(sys.argv)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genjava/genjava_main.py", line 82, in main
    gradle_project.create(args.package, args.output_dir)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genjava/gradle_project.py", line 152, in create
    raise IOError("could not find %s among message packages. Does the that package have a <build_depend> on message_generation in its package.xml?" % msg_pkg_name)
IOError: could not find mask_rcnn_ros among message packages. Does the that package have a <build_depend> on message_generation in its package.xml?
mask_rcnn_ros/CMakeFiles/mask_rcnn_ros_generate_messages_java_gradle.dir/build.make:85: recipe for target 'mask_rcnn_ros/java/mask_rcnn_ros/build.gradle' failed
make[2]: *** [mask_rcnn_ros/java/mask_rcnn_ros/build.gradle] Error 1
CMakeFiles/Makefile2:2693: recipe for target 'mask_rcnn_ros/CMakeFiles/mask_rcnn_ros_generate_messages_java_gradle.dir/all' failed
make[1]: *** [mask_rcnn_ros/CMakeFiles/mask_rcnn_ros_generate_messages_java_gradle.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genjava/cmake/../../../lib/genjava/genjava_gradle_project.py", line 14, in <module>
    genjava.main(sys.argv)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genjava/genjava_main.py", line 82, in main
    gradle_project.create(args.package, args.output_dir)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genjava/gradle_project.py", line 152, in create
    raise IOError("could not find %s among message packages. Does the that package have a <build_depend> on message_generation in its package.xml?" % msg_pkg_name)
IOError: could not find mask_rcnn_ros among message packages. Does the that package have a <build_depend> on message_generation in its package.xml?
mask_rcnn_ros/CMakeFiles/mask_rcnn_ros_generate_messages_java.dir/build.make:84: recipe for target 'mask_rcnn_ros/java/mask_rcnn_ros/build.gradle' failed
make[2]: *** [mask_rcnn_ros/java/mask_rcnn_ros/build.gradle] Error 1
CMakeFiles/Makefile2:2369: recipe for target 'mask_rcnn_ros/CMakeFiles/mask_rcnn_ros_generate_messages_java.dir/all' failed
make[1]: *** [mask_rcnn_ros/CMakeFiles/mask_rcnn_ros_generate_messages_java.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`
I don't know what to do..
my environement uses python3 and the others is installed with your requirements.txt file

**Comment by iKrishneel** [comment]
sorry i overlooked this issue.

`jsk_hsr_wrs` this is a typo and didn't realize. thanks for pointing out.

- unfortunately I am unable to replicate this error.

**Comment by Giessen** [comment]
Catkin_make, workon env,  source workspace, should work.
